branches:
  only:
    - master

language: python
notifications:
  email: false
python:
  - "2.7"
  - "2.6"
install:
  - pip install --use-mirrors -r requirements.txt
  - python setup.py install
script: true
